# Exports
export EDITOR=vim

# Helpers
source /etc/bash_completion

# Qubes
export QUBES_GPG_DOMAIN=secret
export QUBES_GPG_AUTOACCEPT=54000

# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# OCAML / OPAM
. /home/user/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
